[package]
name = "icrc1_registry"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.9"
ic-cdk = "0.11.2"
ic-cdk-macros = "0.8.1"
ic-ledger-types = "0.8.0"
serde = "1"
ic-stable-structures = "0.6.0"

