[package]
name = "swap_trs_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.10"
candid_parser = "0.2.1"
ic-cdk = "0.16"
ic-cdk-macros = "0.16"

# other dependencies
serde = "1"
serde_cbor = "0.11"

