[package]
name = "nfid_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.10"
candid_parser = "0.1.2"
ic-cdk = "0.13"
ic-cdk-macros = "0.13"

# other dependencies
serde = "1"
serde_bytes = "0.11"
serde_cbor = "0.11"

