name: BRL - List Canister Backups
on: 
  workflow_dispatch:
    inputs:
      network_name:
        description: 'Choose applicable network'
        required: true
        type: choice
        options: 
          - dev
          - stage
          - ic
      canister_name:
        description: 'Choose applicable canister'
        required: true
        type: choice
        options:
          - identity_manager
          - signer_eth
          - signer_btc
          - signer_ic
          - vault
      backup_name:
        description: '[optional] Name of the backup folder'
        type: string
      debug_messages:
        description: 'Show debug messages'
        type: choice
        options: 
          - 'false'
          - 'true'

env:
  BACKUP_NAME: ${{ github.event.inputs.backup_name }}
  NETWORK_NAME: ${{ github.event.inputs.network_name }}
  CANISTER_NAME: ${{ github.event.inputs.canister_name }}
  CI_DEBUG: ${{ github.event.inputs.debug_messages }}


jobs:
  List:
    runs-on:
      group: dfx-backup
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo.
        uses: actions/checkout@v4

      - name: Checkout CI repo.
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: internet-identity-labs/ci_libs
          ref: main
          path: ci_libs

      - name: PRE-ACTION => Populate env vars.
        run: |
          source ${{ github.workspace }}/ci_libs/CI_LIBS.sh       
          ci_echo_info "BACKUP_NAME=${BACKUP_NAME}" >&2
          ci_echo_info "NETWORK_NAME=${NETWORK_NAME}" >&2
          ci_echo_info "CANISTER_NAME=${CANISTER_NAME}" >&2

      - name: LIST => List.
        run: |
          source ${{ github.workspace }}/ci_libs/CI_LIBS.sh
          source ./ci_libs/canister_backup_restore.sh

          ci_canister_list_backups "${CANISTER_NAME}" "${NETWORK_NAME}" "${BACKUP_FOLDER}" "${BACKUP_NAME}"
        env:
          BACKUP_FOLDER: /home/ubuntu/backup/
