name: DEV_Pub_Sub_Channel
on: workflow_dispatch

env:
  ENVIRONMENT: dev

jobs:
  Deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/ubuntu/identity_manager

    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Cache Cargo dependencies.
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: PUB SUB CHANNEL | Deploy to ${ENVIRONMENT}
        run: |
          sudo dfx identity use gh_mp_admin

          i=0;
          while :;
          do
            sudo rm -rf .dfx;
            set +e;
            sudo dfx build --network ${ENVIRONMENT} pub_sub_channel;
            sudo dfx canister --no-wallet --network ${ENVIRONMENT} install --mode upgrade pub_sub_channel;
            sleep 5;
            ps=$(sudo dfx canister --network ${ENVIRONMENT} call pub_sub_channel ping);
            set -e;
            ((i=i+1));
            printf 'Try #%s with result: ps-%s\n' "$i" "$ps";
            [[ 20 -gt $i ]] || exit 255;
            [[ "()" != $ps ]] || break;
          done

          cp ./.dfx/ic/canisters/pub_sub_channel/pub_sub_channel.did.d.ts ./ -f
          cp ./.dfx/ic/canisters/pub_sub_channel/pub_sub_channel.did.js ./ -f

      - name: Checkout remote frontend repository to frontend directory.
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: InternetIdentityLabs/MultipassFrontend
          path: frontend

      - name: Update did files.
        run: |
          cp ./pub_sub_channel.did.d.ts ./frontend/src/services/pub-sub-channel/pub_sub_channel.did.d.ts -f
          cp ./pub_sub_channel.did.js ./frontend/src/services/pub-sub-channel/pub_sub_channel_idl.js -f

      - name: Create a pull request to remote frontend repository.
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update did files ${ENVIRONMENT} (pub_sub_channel).
          title: Update did files.
          branch: update-did-files
          path: frontend
          reviewers: plitzenberger
