name: Identity Manager
on: 
  workflow_dispatch:
    inputs:
      network_name:
        description: 'Choose applicable network'
        required: true
        type: choice
        options: 
          - dev
          - ic
      canister_name:
        description: 'Choose applicable canister'
        required: true
        type: choice
        options:
          - identity_manager_test_replica
          - identity_manager
      debug_messages:
        description: 'Show debug messages'
        type: choice
        options: 
          - 'false'
          - 'true'
      confirmation:
        description: 'For the ic deployment - confirm your choice by typing "Yes"'
        type: string

env:
  NETWORK_NAME: ${{ github.event.inputs.network_name }}
  CANISTER_NAME: ${{ github.event.inputs.canister_name }}
  DEBUG: ${{ github.event.inputs.debug_messages }}


jobs:
  Deploy:
    runs-on: ubuntu-latest
    container:
      image: identitylabs/dfxctl:0.10.1-compiled
    defaults:
      run:
        shell: bash

    steps:
      - name: INPUT => Checks.
        if: ${{ (github.event.inputs.network_name == 'ic') && (github.event.inputs.confirmation != 'Yes') }}
        run: |
          echo "[ERROR] You have try release to network 'ic' without or with wrong confirmation phrase" >&2
          exit 1

      - name: DFX => Write identity.
        run: |
          mkdir -p $ID_PATH
          echo $GH_MP_ADMIN_PEM >> $ID_PATH/identity.pem
          sed -i 's/\\r\\n/\r\n/g' $ID_PATH/identity.pem
        env:
          GH_MP_ADMIN_PEM: ${{secrets.GH_MP_ADMIN_PEM}}
          ID_PATH: /root/.config/dfx/identity/gh_mp_admin

      - name: DFX => Start.
        run: |
          dfx_run &
          sleep 60
        working-directory: /default_project
        env:
          HOME: /root

      - name: Checkout repo.
        uses: actions/checkout@v3

      - name: Cache Cargo dependencies.
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            /cargo
            /cargo_target
            target/
          key: ${{ runner.os }}-cargo-${{ github.event.inputs.network_name }}-${{ github.event.inputs.canister_name }}-${{ hashFiles('**/Cargo.lock') }}

      - name: PRE-BUILD => Populate env vars.
        run: |
          source .github/workflows/CI_LIBS.sh
          export HOME=/root

          echo_debug "Installing jq"
          apt-get update && apt-get install -y --no-install-recommends jq

          echo_debug "Getting values from dfx.json"
          if ! canister_data=$(cat dfx.json | jq -er ".canisters.${CANISTER_NAME}"); then
            echo_error "Can't found canister '${CANISTER_NAME}' data from dfx.json" >&2
            exit 1
          fi

          CANISTER_DID="$(cat dfx.json | jq -er ".canisters.${CANISTER_NAME}.candid")"
          CANISTER_WASM="$(cat dfx.json | jq -er ".canisters.${CANISTER_NAME}.wasm")"
          CANISTER_BRANCH="${GITHUB_REF_NAME////-}"
            
          echo "CANISTER_DID=${CANISTER_DID}" >> $GITHUB_ENV
          echo "CANISTER_WASM=${CANISTER_WASM}" >> $GITHUB_ENV
          echo "CANISTER_BRANCH=${CANISTER_BRANCH}" >> $GITHUB_ENV
          
          echo_info "NETWORK_NAME=${NETWORK_NAME}" >&2
          echo_info "CANISTER_NAME=${CANISTER_NAME}" >&2
          echo_info "CANISTER_DID=${CANISTER_DID}" >&2
          echo_info "CANISTER_WASM=${CANISTER_WASM}" >&2
          echo_info "CANISTER_BRANCH=${CANISTER_BRANCH}" >&2
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: BUILD => Show current configuration.
        run: |
          source .github/workflows/CI_LIBS.sh
          export HOME=/root

          dfx identity use gh_mp_admin

          echo_debug "dfx canister --network '${NETWORK_NAME}' call '${CANISTER_NAME}' get_config" >&2
          dfx canister --network "${NETWORK_NAME}" call "${CANISTER_NAME}" get_config

      - name: BUILD => Build the canister.
        run: |
          source .github/workflows/CI_LIBS.sh
          export HOME=/root

          dfx identity use gh_mp_admin

          rm -rf .dfx;
          echo_debug "dfx build --network '${NETWORK_NAME}' '${CANISTER_NAME}'" >&2
          dfx build --network "${NETWORK_NAME}" "${CANISTER_NAME}"

      - name: DEPLOY PROD => Upgrade the identity_manager_replica canister.
        if: ${{ (github.event.inputs.canister_name == 'identity_manager') && (github.event.inputs.network_name == 'ic') }}
        run: |
          source .github/workflows/CI_LIBS.sh
          export HOME=/root

          dfx identity use gh_mp_admin

          DEBUG="true"

          echo_debug "dfx canister --network '${NETWORK_NAME}' install --mode upgrade 'identity_manager_replica'" >&2
          if ! result=$(dfx canister --network "${NETWORK_NAME}" install --mode upgrade "identity_manager_replica"); then
            echo_error "Upgrade failed ${result}" >&2
            exit 1
          fi

          echo_debug "Command output was '${result}'" >&2

          # If hash the same - than fail deploy
          if echo "${result}" | grep -q 'Module hash [[:alnum:]]+ is already installed'; then
            echo_error "${result}" >&2
            exit 1
          else
            echo_success "Canister 'identity_manager_replica' was upgraded" >&2
          fi

      - name: DEPLOY PROD => Send configuration to the identity_manager_replica canister.
        if: ${{ (github.event.inputs.canister_name == 'identity_manager') && (github.event.inputs.network_name == 'ic') }}
        run: |
          source .github/workflows/CI_LIBS.sh
          export HOME=/root

          dfx identity use gh_mp_admin

          DEBUG="true"

          CANISTER_DATA_NAME_VAR="CANISTER_CONFIG_TEST_DATA"

          CANISTER_DATA="$(sed "s/PLACEHOLDER_GITHUB_REF_NAME/${CANISTER_BRANCH}/" <<< "${!CANISTER_DATA_NAME_VAR}" | sed "s/PLACEHOLDER_GITHUB_SHA/${GITHUB_SHA}/")"

          echo_debug "dfx canister --network '${NETWORK_NAME}' call 'identity_manager_replica' configure '${CANISTER_DATA}'" >&2
          if ! result=$(dfx canister --network "${NETWORK_NAME}" call "identity_manager_replica" configure "${CANISTER_DATA}"); then
            echo_error "Configure failed ${result}" >&2
            exit 1
          fi

          echo_debug "Command output was '${result}'" >&2

          # If '()' not found - than fail
          if ! echo "${result}" | grep -q '()'; then
            echo_error "${result}" >&2
            exit 1
          else
            echo_success "${result}" >&2
          fi
        env:
          CANISTER_CONFIG_TEST_DATA: >-
            (
                record {
                    lambda = opt principal "mltzx-rlg5h-qzcpp-xdp7e-56vnr-cbdjf-e6x5q-gzm2d-2soup-wtk5n-5qe";
                    whitelisted_canisters = opt vec {principal "bryxc-zqaaa-aaaal-aajga-cai"};
                    git_branch = opt "PLACEHOLDER_GITHUB_REF_NAME";
                    commit_hash = opt "PLACEHOLDER_GITHUB_SHA";
                }
            )

      - name: TEST PROD => Get Account from the identity_manager_replica canister.
        if: ${{ (github.event.inputs.canister_name == 'identity_manager') && (github.event.inputs.network_name == 'ic') }}
        run: |
          source .github/workflows/CI_LIBS.sh
          export HOME=/root

          dfx identity use gh_mp_admin

          DEBUG="true"

          echo_debug "dfx canister --network '${NETWORK_NAME}' call 'identity_manager_replica' get_account" >&2
          if ! result=$(dfx canister --network "${NETWORK_NAME}" call "identity_manager_replica" get_account) || [ -z "${result}" ]; then
            echo_error "Test failed - call to canister unsuccessful" >&2
            exit 1
          fi

          echo_debug "Command output was '${result}'" >&2

          # If 'anchor' not found - than fail
          if ! echo "${result}" | grep -q 'anchor'; then
            echo_error "Test failed - 'anchor' - was not found" >&2
            exit 1
          else
            echo_success "${result}"
          fi

      - name: DEPLOY => Upgrade the canister.
        run: |
          source .github/workflows/CI_LIBS.sh
          export HOME=/root

          dfx identity use gh_mp_admin

          if [ "${NETWORK_NAME}" == 'ic' ] && [ "${CANISTER_NAME}" == 'identity_manager' ]; then
            echo_warn "Performing PROD canister Upgrade" >&2
            DEBUG="true"
          fi

          echo_debug "dfx canister --network '${NETWORK_NAME}' install --mode upgrade '${CANISTER_NAME}'" >&2
          if ! result=$(dfx canister --network "${NETWORK_NAME}" install --mode upgrade "${CANISTER_NAME}"); then
            echo_error "Upgrade failed ${result}" >&2
            exit 1
          fi

          echo_debug "Command output was '${result}'" >&2

          # If hash the same - than fail deploy
          if echo "${result}" | grep -q 'Module hash [[:alnum:]]+ is already installed'; then
            echo_error "${result}" >&2
            exit 1
          else
            echo_success "Canister '${CANISTER_NAME}' was upgraded" >&2
          fi

      - name: DEPLOY => Send configuration to the canister.
        run: |
          source .github/workflows/CI_LIBS.sh
          export HOME=/root

          dfx identity use gh_mp_admin

          if [ "${NETWORK_NAME}" == 'ic' ] && [ "${CANISTER_NAME}" == 'identity_manager' ]; then
            echo_warn "Performing PROD config Update" >&2
            DEBUG="true"
            CANISTER_DATA_NAME_VAR="CANISTER_CONFIG_PROD_DATA"
          else
            CANISTER_DATA_NAME_VAR="CANISTER_CONFIG_DATA"
          fi

          CANISTER_DATA="$(sed "s/PLACEHOLDER_GITHUB_REF_NAME/${CANISTER_BRANCH}/" <<< "${!CANISTER_DATA_NAME_VAR}" | sed "s/PLACEHOLDER_GITHUB_SHA/${GITHUB_SHA}/")"

          # Configure command
          echo_debug "dfx canister --network '${NETWORK_NAME}' call '${CANISTER_NAME}' configure '${CANISTER_DATA}'" >&2
          if ! result=$(dfx canister --network "${NETWORK_NAME}" call "${CANISTER_NAME}" configure "${CANISTER_DATA}"); then
            echo_error "Configure failed ${result}" >&2
            exit 1
          fi

          echo_debug "Command output was '${result}'" >&2

          # If '()' not found - than fail
          if ! echo "${result}" | grep -q '()'; then
            echo_error "${result}" >&2
            exit 1
          else
            echo_success "${result}" >&2
          fi

          # Sync command
          echo_info "Synching controllers for the canister." >&2
          echo_debug "dfx canister --network '${NETWORK_NAME}' call '${CANISTER_NAME}' sync_controllers" >&2
          if ! result=$(dfx canister --network "${NETWORK_NAME}" call "${CANISTER_NAME}" sync_controllers); then
            echo_warn "Synching controllers failed ${result}" >&2
          else
            echo_success "${result}" >&2
          fi
          
        env:
          CANISTER_CONFIG_DATA: >-
            (
              record {
                ii_canister_id = opt principal "nprnb-waaaa-aaaaj-qax4a-cai";
                lambda = opt principal "mltzx-rlg5h-qzcpp-xdp7e-56vnr-cbdjf-e6x5q-gzm2d-2soup-wtk5n-5qe";
                git_branch = opt "PLACEHOLDER_GITHUB_REF_NAME";
                commit_hash = opt "PLACEHOLDER_GITHUB_SHA";
              }
            )
          CANISTER_CONFIG_PROD_DATA: >-
            (
              record {
                ii_canister_id = opt principal "rdmx6-jaaaa-aaaaa-aaadq-cai";
                lambda = opt principal "mltzx-rlg5h-qzcpp-xdp7e-56vnr-cbdjf-e6x5q-gzm2d-2soup-wtk5n-5qe";
                heartbeat = opt 900;
                backup_canister_id = opt "bv5d4-nyaaa-aaaap-qaaba-cai";
                git_branch = opt "PLACEHOLDER_GITHUB_REF_NAME";
                commit_hash = opt "PLACEHOLDER_GITHUB_SHA";
              }
            )

      - name: TEST => Get Account from the canister.
        run: |
          source .github/workflows/CI_LIBS.sh
          export HOME=/root

          dfx identity use gh_mp_admin

          echo_debug "dfx canister --network '${NETWORK_NAME}' call '${CANISTER_NAME}' get_account" >&2
          if ! result=$(dfx canister --network "${NETWORK_NAME}" call "${CANISTER_NAME}" get_account) || [ -z "${result}" ]; then
            echo_error "Test failed - call to canister unsuccessful" >&2
            exit 1
          fi

          echo_debug "Command output was '${result}'" >&2

          # If 'anchor' not found - than fail
          if ! echo "${result}" | grep -q 'anchor'; then
            echo_error "Test failed - 'anchor' - was not found" >&2
            exit 1
          else
            echo_success "${result}"
          fi

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.CANISTER_WASM }}
          path: ${{ github.workspace }}/${{ env.CANISTER_WASM }}

      - name: Frontend => Checkout repo.
        uses: actions/checkout@v3
        if: ${{ github.event.inputs.canister_name == 'identity_manager' }}
        with:
          token: ${{ secrets.PAT }}
          repository: internet-identity-labs/nfid-frontend
          ref: main
          path: frontend

      - name: Frontend => Update did files.
        if: ${{ github.event.inputs.canister_name == 'identity_manager' }}
        run: |
          cp -f "./.dfx/${NETWORK_NAME}/canisters/${CANISTER_NAME}/${CANISTER_NAME}.did.d.ts" "./frontend/src/services/identity-manager/${CANISTER_NAME}.did.d.ts"
          cp -f "./.dfx/${NETWORK_NAME}/canisters/${CANISTER_NAME}/${CANISTER_NAME}.did.js" "./frontend/src/services/identity-manager/${CANISTER_NAME}_idl.js"

      - name: Frontend => Format did files.
        if: ${{ github.event.inputs.canister_name == 'identity_manager' }}
        run: |
          npm install --global yarn
          cd ./frontend
          yarn
          yarn prettier --write ./src/services/identity-manager/${CANISTER_NAME}.did.d.ts
          yarn prettier --write ./src/services/identity-manager/${CANISTER_NAME}_idl.js
          git diff

      - name: Frontend => Create a pull request.
        if: ${{ github.event.inputs.canister_name == 'identity_manager' }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: "ci: update ${{ env.NETWORK_NAME }} - ${{ env.CANISTER_NAME }} did files"
          title: "ci: update ${{ env.NETWORK_NAME }} - ${{ env.CANISTER_NAME }} did files"
          branch: update-did-files
          path: frontend
          reviewers: plitzenberger
