name: BEItest
on:
    push:
    workflow_dispatch:

jobs:
    test:
        name: Unit & Integration tests
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash

        steps:
            - name: Checkout nfid-wallet-server repo
              uses: actions/checkout@v4

            - name: Checkout ci_libs repo
              uses: actions/checkout@v4
              with:
                  repository: internet-identity-labs/ci_libs
                  ref: main
                  path: ci_libs
                  token: ${{ secrets.PAT }}

            - name: Install dfx
              run: |
                  export DFX_VERSION=0.22.0
                  export DFXVM_INIT_YES=true
                  sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
                  echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: wasm32-unknown-unknown
                  override: true

            - name: Cache Cargo dependencies
              uses: actions/cache@v4
              with:
                  key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      cargo-${{ runner.os }}-
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target

            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                  path: ~/.m2/repository
                  key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      maven-${{ runner.os }}-

            - name: Versions
              run: |
                  source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"
                  ci_versions
            - name: Setup DFX identity
              run: |
                  source "${{ github.workspace }}/ci_libs/CI_LIBS.sh"

                  if ! [ -f "${HOME}/.config/dfx/identity/test_admin/identity.pem" ]; then
                    dfx identity new test_admin --storage-mode plaintext
                  fi
                  cp -f identity-manager-itest/src/test/resources/identity/identity.pem \
                    ${HOME}/.config/dfx/identity/test_admin

                  if pgrep icx-proxy > /dev/null; then
                    ci_echo_warn "Stopping icx-proxy..." >&2
                    kill -9 $(pgrep icx-proxy)
                  fi

            - name: Build and run JS integration tests
              run: |
                  pushd identity-manager-itest
                  npm ci && npm run test

            - name: Build and run integration tests
              run: |
                  pushd identity-manager-itest
                  mvn test --no-transfer-progress
