name: BEItest
on: [push, workflow_dispatch]


jobs:
  test:
    runs-on: [self-hosted, Linux, X64]
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Cache Cargo dependencies.
        uses: actions/cache@v2
        with:
          path: |
            /home/ubuntu/.cargo/bin/
            /home/ubuntu/.cargo/registry/index/
            /home/ubuntu/.cargo/registry/cache/
            /home/ubuntu/.cargo/git/db/
            /home/ubuntu/.cargo/cargo_target/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: BE Unit Test
        run: |
          cargo test -- --test-threads=1

      - name: BE ITest
        run: |
          if ! [ -f "/home/ubuntu/.config/dfx/identity/test_admin/identity.pem" ]; then
            dfx identity new test_admin
          fi

          cp -f identity-manager-itest/src/test/resources/identity/identity.pem /home/ubuntu/.config/dfx/identity/test_admin
          
          pushd identity-manager-itest
          mvn -e -X test --no-transfer-progress

      - name: BE Integration Tests JS
        run: npm i && npm run test
