name: BEItest
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: [self-hosted, Linux, X64]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Cache Cargo dependencies.
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/cargo_target/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: BE Unit Test
        run: |
          cargo test -- --test-threads=1

      - name: BE ITest
        run: |
          dfx identity new test_admin
          cp -f identity-manager-itest/src/test/resources/identity/identity.pem ~/.config/dfx/identity/test_admin
          cd identity-manager-itest
          mvn test --no-transfer-progress

      - name: BE Integration Tests JS
        run: npm i && npm run test
